# -*- coding: utf-8 -*-
"""TarotAiApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWuviWgGIsz9v9VRJFASFG0XbZ_bqgFT

This program is designed to simulate a tarot card reading by randomly drawing six tarot cards from a pre-defined tarot deck, determining whether each card is drawn upright or reversed, and then using GPT-3 (or its successor models) to generate a personalized tarot reading based on those cards.
"""

!pip install openai==0.28

import random
import openai

# Defined the Tarot Card Class
class TarotCard:
    def __init__(self, name, meaning, meaning_reversed):
        self.name = name
        self.meaning = meaning
        self.meaning_reversed = meaning_reversed

    def __str__(self):
        return f"{self.name}: {self.meaning} (Reversed: {self.meaning_reversed})"

# Tarot Deck inserted into a dictionary with name, meaning and inversed meaning
tarot_deck = {
    'The Fool': ('New beginnings, innocence, spontaneity, a free spirit', 'Recklessness, taken advantage of, inconsideration'),
    'The Magician': ('Manifestation, resourcefulness, power, inspired action', 'Manipulation, poor planning, untapped talents'),
    'The High Priestess': ('Intuition, sacred knowledge, divine feminine, the subconscious mind', 'Secrets, disconnected from intuition, withdrawal and silence'),
    'The Empress': ('Femininity, beauty, nature, nurturing, abundance', 'Creative block, dependence on others'),
    'The Emperor': ('Authority, establishment, structure, a father figure', 'Domination, excessive control, lack of discipline, inflexibility'),
    'The Hierophant': ('Spiritual wisdom, religious beliefs, conformity, tradition, institutions', 'Personal beliefs, freedom, challenging the status quo'),
    'The Lovers': ('Love, harmony, relationships, values alignment, choices', 'Self-love, disharmony, imbalance, misalignment of values'),
    'The Chariot': ('Control, willpower, success, action, determination', 'Self-discipline, opposition, lack of direction'),
    'Strength': ('Courage, bravery, confidence, compassion, inner strength', 'Self-doubt, weakness, insecurity'),
    'The Hermit': ('Soul-searching, introspection, being alone, inner guidance', 'Isolation, loneliness, withdrawal'),
    'Wheel of Fortune': ('Good luck, karma, life cycles, destiny, a turning point', 'Bad luck, resistance to change, breaking cycles'),
    'Justice': ('Justice, fairness, truth, cause and effect, law', 'Unfairness, lack of accountability, dishonesty'),
    'The Hanged Man': ('Pause, surrender, letting go, new perspectives', 'Delays, resistance, stalling, indecision'),
    'Death': ('Endings, change, transformation, transition', 'Resistance to change, personal transformation, inner purging'),
    'Temperance': ('Balance, moderation, patience, purpose', 'Imbalance, excess, self-healing, re-alignment'),
    'The Devil': ('Shadow self, attachment, addiction, restriction, sexuality', 'Releasing limiting beliefs, exploring dark thoughts, detachment'),
    'The Tower': ('Sudden change, upheaval, chaos, revelation, awakening', 'Personal transformation, fear of change, averting disaster'),
    'The Star': ('Hope, faith, purpose, renewal, spirituality', 'Lack of faith, despair, self-trust, disconnection'),
    'The Moon': ('Illusion, fear, anxiety, subconscious, intuition', 'Release of fear, repressed emotion, inner confusion'),
    'The Sun': ('Positivity, fun, warmth, success, vitality', 'Inner child, feeling down, overly optimistic'),
    'Judgement': ('Judgement, rebirth, inner calling, absolution', 'Self-doubt, inner critic, ignoring the call'),
    'The World': ('Completion, integration, accomplishment, travel', 'Seeking personal closure, short-cuts, delays'),
    'Ace of Cups': ('New relationships, compassion, creativity', 'Emotional loss, blocked creativity, emptiness'),'Two of Cups': ('Unified love, partnership, mutual attraction', 'Self-love, break-ups, disharmony, distrust'),
    'Three of Cups': ('Celebration, friendship, creativity, community', 'Independence, alone time, hardcore partying, ‘three’s a crowd’'),
    'Four of Cups': ('Meditation, contemplation, apathy, reevaluation', 'Retreat, withdrawal, checking in for alignment'),
    'Five of Cups': ('Regret, failure, disappointment, pessimism', 'Personal setbacks, self-forgiveness, moving on'),
    'Six of Cups': ('Revisiting the past, childhood memories, innocence, joy', 'Living in the past, forgiveness, lacking playfulness'),
    'Seven of Cups': ('Opportunities, choices, wishful thinking, illusion', 'Alignment, personal values, overwhelmed by choices'),
    'Eight of Cups': ('Disappointment, abandonment, withdrawal, escapism', 'Trying one more time, indecision, aimless drifting'),
    'Nine of Cups': ('Contentment, satisfaction, gratitude, wish come true', 'Inner happiness, materialism, dissatisfaction'),
    'Ten of Cups': ('Divine love, blissful relationships, harmony, alignment', 'Disconnection, misaligned values, struggling relationships'),
    'Page of Cups': ('Creative opportunities, intuitive messages, curiosity, possibility', 'New ideas, doubting intuition, creative blocks, emotional immaturity'),
    'Knight of Cups': ('Romance, charm, imagination, beauty', 'Overactive imagination, unrealistic, jealous, moody'),
    'Queen of Cups': ('Compassionate, caring, emotionally stable, intuitive, in flow', 'Inner feelings, self-care, co-dependency'),
    'King of Cups': ('Emotionally balanced, compassionate, diplomatic', 'Emotional manipulation, moodiness, volatility'),
    'Ace of Pentacles': ('A new financial or career opportunity, manifestation, abundance', 'Lost opportunity, lack of planning and foresight'),
    'Two of Pentacles': ('Multiple priorities, time management, adaptability, balance', 'Over-committed, disorganization, reprioritization'),
    'Three of Pentacles': ('Teamwork, collaboration, learning, implementation', 'Disharmony, misalignment, working alone'),
    'Four of Pentacles': ('Saving money, security, conservatism, scarcity, control', 'Over-spending, greed, self-protection'),
    'Five of Pentacles': ('Financial loss, poverty, lack mindset, isolation, worry', 'Recovery from financial loss, spiritual poverty'),
    'Six of Pentacles': ('Giving, receiving, sharing wealth, generosity, charity', 'Self-care, unpaid debts, one-sided charity'),
    'Seven of Pentacles': ('Long-term view, sustainable results, perseverance, investment', 'Lack of long-term vision, limited success or reward'),
    'Eight of Pentacles': ('Apprenticeship, repetitive tasks, skill development, mastery', 'Self-development, perfectionism, misdirected activity'),
    'Nine of Pentacles': ('Abundance, luxury, self-sufficiency, financial independence', 'Self-worth, over-investment in work, hustling'),
    'Ten of Pentacles': ('Wealth, financial security, family, long-term success, contribution', 'The dark side of wealth, financial failure or loss'),
    'Page of Pentacles': ('Manifestation, financial opportunity, skill development', 'Lack of progress, procrastination, learn from failure'),
    'Knight of Pentacles': ('Hard work, productivity, routine, conservatism', 'Self-discipline, boredom, feeling ‘stuck’, perfectionism'),
    'Queen of Pentacles': ('Nurturing, practical, providing financially, a working parent', 'Financial independence, self-care, work-home conflict'),
    'King of Pentacles': ('Wealth, business, leadership, security, discipline, abundance', 'Financially inept, obsessed with wealth and status, stubborn'),
    'Ace of Swords': ('Breakthrough, clarity, sharp mind', 'Inner clarity, re-thinking an idea, clouded judgement'),
    'Two of Swords': ('Difficult decisions, weighing up options, an impasse, avoidance', 'Indecision, confusion, information overload, stalemate'),
    'Three of Swords': ('Heartbreak, emotional pain, sorrow, grief, hurt', 'Negative self-talk, releasing pain, optimism, forgiveness'),
    'Four of Swords': ('Rest, relaxation, meditation, contemplation, recuperation', 'Exhaustion, burnout, deep contemplation, stagnation'),
    'Five of Swords': ('Conflict, disagreements, competition, defeat, winning at all costs', 'Reconciliation, making amends, past resentment'),
    'Six of Swords': ('Transition, change, rite of passage, releasing baggage', 'Personal transition, resistance to change, unfinished business'),
    'Seven of Swords': ('Betrayal, deception, getting away with something, acting strategically', 'Imposter syndrome, keeping secrets, self-deceit'),
    'Eight of Swords': ('Negative thoughts, self-imposed restriction, imprisonment, victim mentality', 'Self-limiting beliefs, inner critic, releasing negative thoughts, open to new perspectives'),
    'Nine of Swords': ('Anxiety, worry, fear, depression, nightmares', 'Inner turmoil, deep-seated fears, secrets, releasing worry'),
    'Ten of Swords': ('Painful endings, deep wounds, betrayal, loss, crisis', 'Recovery, regeneration, resisting an inevitable end'),
    'Page of Swords': ('New ideas, curiosity, thirst for knowledge, new ways of communicating', 'Self-expression, all talk and no action, haphazard action, haste'),
    'Knight of Swords': ('Ambitious, action-oriented, driven to succeed, fast-thinking', 'Restless, unfocused, impulsive, burnt out'),
    'Queen of Swords': ('Independent, unbiased judgement, clear boundaries, direct communication', 'Overly-emotional, easily influenced, bitchy, cold-hearted'),
    'King of Swords': ('Mental clarity, intellectual power, authority, truth', 'Quiet power, inner truth, misuse of power, manipulation'),
    'Ace of Wands': ('Inspiration, new opportunities, growth, potential', 'An emerging idea, lack of direction, distractions, delays'),
    'Two of Wands': ('Future planning, progress, decisions, discovery', 'Personal goals, inner alignment, fear of unknown, lack of planning'),
    'Three of Wands': ('Progress, expansion, foresight, overseas opportunities', 'Playing small, lack of foresight, unexpected delays'),
    'Four of Wands': ('Celebration, joy, harmony, relaxation, homecoming', 'Personal celebration, inner harmony, conflict with others, transition'),
    'Five of Wands': ('Conflict, disagreements, competition, tension, diversity', 'Inner conflict, conflict avoidance, tension release'),
    'Six of Wands': ('Success, public recognition, progress, self-confidence', 'Private achievement, personal definition of success, fall from grace, egotism'),
    'Seven of Wands': ('Challenge, competition, protection, perseverance', 'Exhaustion, giving up, overwhelmed'),
    'Eight of Wands': ('Movement, fast-paced change, action, alignment, air travel', 'Delays, frustration, resisting change, internal alignment'),
    'Nine of Wands': ('Resilience, courage, persistence, test of faith, boundaries', 'Inner resources, struggling, overwhelmed, defensive, paranoia'),
    'Ten of Wands': ('Burden, extra responsibility, hard work, completion', 'Doing it all, carrying the burden, delegation, release'),
    'Page of Wands': ('Inspiration, ideas, discovery, limitless potential, free spirit', 'Newly-formed ideas, redirecting energy, self-limiting beliefs, a spiritual path'),
    'Knight of Wands': ('Energy, passion, inspired action, adventure, impulsiveness', 'Passion project, haste, scattered energy, delays, frustration'),
    'Queen of Wands': ('Courage, confidence, independence, social butterfly, determination', 'Self-respect, self-confidence, introverted, re-establish sense of self'),
    'King of Wands': ('Natural-born leader, vision, entrepreneur, honor', 'Impulsiveness, haste, ruthless, high expectations'),
}

# Created a list of TarotCard objects
tarot_cards = [TarotCard(name, meaning, meaning_reversed) for name, (meaning, meaning_reversed) in tarot_deck.items()]

# Print the list of TarotCard objects in the new format
#for card in tarot_cards:
  #print(card)
  #print("---") # Optional separator between cards

#Inputs used to cumstomize the AI prompt
name = input("Welcome! May I have your name?: ")
intention = input("If you have a specific intention for this reading, please share it. Otherwise, you can leave this blank: ")

# Draw 6 random cards and determine their orientation. These will be used to generate the AI prompt
def draw_random_cards(tarot_cards, num_cards=6):
    drawn_cards = []
    for _ in range(num_cards):
        card = random.choice(tarot_cards) # Choose a random card from tarot_cards list
        orientation = random.choice(['upright', 'reversed'])  # Determine orientation upright or inverse
        drawn_cards.append((card, orientation))
    return drawn_cards

# prompt = card meaning + name + intention + parameters
def generate_tarot_prompt(drawn_cards):
    prompt = f"This is a tarot reading for {name}.\n"
    if intention:
        prompt += f"Whose intention is: {intention}.\n\n"
    else:
        prompt += "They have not set a particular intention for this reading.\n\n"
    prompt += "You have drawn the following tarot cards:\n\n"

    for card, orientation in drawn_cards:
        if orientation == 'upright':
            meaning = card.meaning
        else:
            meaning = card.meaning_reversed

        prompt += f"Card: {card.name}\n"
        prompt += f"Orientation: {orientation.capitalize()}\n"
        prompt += f"Meaning: {meaning}\n\n"

    prompt += ("Based on these cards and their orientations, generate a detailed tarot reading for the user. "
               "Use varying language and intuition to provide guidance on the key themes presented by the cards.")

    return prompt

# Function to interact with OpenAI GPT to get the tarot reading
def get_tarot_reading(prompt):
    openai.api_key = 'INSERT KEY HERE'

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful and insightful tarot reader."}, # Set the system role
            {"role": "user", "content": prompt} #prompt as user message
        ],
        max_tokens=200,
        n=1,
        stop=None,
        temperature=0.8 #higher temperature to allow for more flexibility in AI response
    )

    return response.choices[0].message['content'].strip() # Access content from message

# Draw 6 random tarot cards
drawn_cards = draw_random_cards(tarot_cards)

# Generate the GPT-3 prompt
tarot_prompt = generate_tarot_prompt(drawn_cards)

# Print the generated prompt for debugging (optional)
print(tarot_prompt)

# Generate reading using AI
reading = get_tarot_reading(tarot_prompt)
# Print the tarot reading with one sentence per line
print("\nTarot Reading:\n")
for sentence in reading.split(". "):
    print(sentence.strip() + ".")

print("May your day be filled with love light!")

